inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'src/**/*'
    - 'vendor/bundle/**/*'

Metrics/LineLength:
  Max: 120

Layout/EndOfLine:
  EnforcedStyle: lf

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/EmptyMethod:
  EnforcedStyle: expanded

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
  ExcludedMethods:
    - describe

Style/FrozenStringLiteralComment:
  EnforcedStyle: when_needed

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
